alterations to symlink makefile target

diff --git a/packer/Makefile b/packer/Makefile
--- a/packer/Makefile
+++ b/packer/Makefile
@@ -54,10 +54,14 @@ help:
 
 .PHONY: sshkeyfile
 sshkeyfile: ## Symlink local sshkey to directory to use in Packer
-	@[ -f ./$(SSH_PRIVATE_KEY_FILE) ] && ( echo "[INFO] Found sshkey: ./$(SSH_PRIVATE_KEY_FILE)" ) || ( \
-	  [ -f ~/.ssh/$(SSH_PRIVATE_KEY_FILE) ] && \
-	    ln -sf ~/.ssh/$(SSH_PRIVATE_KEY_FILE) ./$(SSH_PRIVATE_KEY_FILE) || \
-	      printf "\033[0;31m[ERROR] Create a copy of sshkey in current directory (or symlink): e.g ./$(SSH_PRIVATE_KEY_FILE)\n"; exit 1 )
+	@if [ -f ./$(SSH_PRIVATE_KEY_FILE) ]; \
+	  then echo "[INFO] Found sshkey: ./$(SSH_PRIVATE_KEY_FILE)"; \
+	elif [ -f ~/.ssh/$(SSH_PRIVATE_KEY_FILE) ]; \
+	  then echo "[INFO] Found sshkey creating symlink: ~/.ssh/$(SSH_PRIVATE_KEY_FILE)"; \
+	    ln -sf ~/.ssh/$(SSH_PRIVATE_KEY_FILE) ./$(SSH_PRIVATE_KEY_FILE); \
+	else \
+          echo "\033[0;31m[ERROR] Create a copy of sshkey in current directory (or symlink): e.g ./$(SSH_PRIVATE_KEY_FILE)\n"; exit 1; \
+	fi;
 
 .PHONY: validate
 validate: sshkeyfile ## Run packer validate using defined variables
